/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Euclebio
 */
public class MenuChair extends javax.swing.JFrame {

    /**
     * Creates new form MenuChair
     */
    public MenuChair() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalChair = new javax.swing.JPanel();
        BotaoLogout = new javax.swing.JButton();
        BotaoVerifiAvali = new javax.swing.JButton();
        BotaoAtribuirArtigo = new javax.swing.JButton();
        BotaoCriarEvento = new javax.swing.JButton();
        BotaoPromoverAutor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu CHAIR");

        PanelPrincipalChair.setToolTipText("Menu Chair");

        BotaoLogout.setText("Logout");
        BotaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoutActionPerformed(evt);
            }
        });

        BotaoVerifiAvali.setText("Verificar Avaliacao");
        BotaoVerifiAvali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerifiAvaliActionPerformed(evt);
            }
        });

        BotaoAtribuirArtigo.setText("Atribuir Artigo a Avaliador ");
        BotaoAtribuirArtigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAtribuirArtigoActionPerformed(evt);
            }
        });

        BotaoCriarEvento.setText("Criar Evento");
        BotaoCriarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCriarEventoActionPerformed(evt);
            }
        });

        BotaoPromoverAutor.setText("Promover Autor");
        BotaoPromoverAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPromoverAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalChairLayout = new javax.swing.GroupLayout(PanelPrincipalChair);
        PanelPrincipalChair.setLayout(PanelPrincipalChairLayout);
        PanelPrincipalChairLayout.setHorizontalGroup(
            PanelPrincipalChairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalChairLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(PanelPrincipalChairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalChairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BotaoVerifiAvali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoCriarEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAtribuirArtigo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(BotaoPromoverAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        PanelPrincipalChairLayout.setVerticalGroup(
            PanelPrincipalChairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalChairLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(BotaoVerifiAvali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoPromoverAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoAtribuirArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCriarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalChair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalChair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCriarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCriarEventoActionPerformed
        CadastrarEvento cadastro = new CadastrarEvento(this, true);
        cadastro.setSize(600,430);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoCriarEventoActionPerformed

    private void BotaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoutActionPerformed
        this.dispose();
        Menu2 menu = new Menu2();
        menu.setVisible(true);
        menu.setDefaultCloseOperation(EXIT_ON_CLOSE);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_BotaoLogoutActionPerformed

    private void BotaoVerifiAvaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerifiAvaliActionPerformed
        VerificarAvaliacao cadastro = new VerificarAvaliacao(this, true);
        cadastro.setSize(600,500);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoVerifiAvaliActionPerformed

    private void BotaoPromoverAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPromoverAutorActionPerformed
        PromoverUsuario cadastro = new PromoverUsuario(this, true);
        cadastro.setSize(520,400);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoPromoverAutorActionPerformed

    private void BotaoAtribuirArtigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAtribuirArtigoActionPerformed
        AtribuirArtAvaliador cadastro = new AtribuirArtAvaliador(this, true);
        cadastro.setSize(600,430);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoAtribuirArtigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuChair menu = new MenuChair();
                menu.setVisible(true);
                menu.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                menu.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAtribuirArtigo;
    private javax.swing.JButton BotaoCriarEvento;
    private javax.swing.JButton BotaoLogout;
    private javax.swing.JButton BotaoPromoverAutor;
    private javax.swing.JButton BotaoVerifiAvali;
    private javax.swing.JPanel PanelPrincipalChair;
    // End of variables declaration//GEN-END:variables
}
