/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Usuarios;

/**
 *
 * @author Aluno
 */
public class MenuAvaliador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAvaliador
     */
    Usuarios x = new Usuarios();
    public MenuAvaliador(Usuarios temp) {
        initComponents();
        x = temp;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalAvaliador = new javax.swing.JPanel();
        BotaoAvaliarArtigos = new javax.swing.JButton();
        BotaoLogoutAvaliador = new javax.swing.JButton();
        BotaoAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Avaliador");

        PanelPrincipalAvaliador.setToolTipText("");

        BotaoAvaliarArtigos.setText("Avaliar artigos");
        BotaoAvaliarArtigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAvaliarArtigosActionPerformed(evt);
            }
        });

        BotaoLogoutAvaliador.setText("Logout");
        BotaoLogoutAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoutAvaliadorActionPerformed(evt);
            }
        });

        BotaoAlterar.setText("Alterar Conta");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalAvaliadorLayout = new javax.swing.GroupLayout(PanelPrincipalAvaliador);
        PanelPrincipalAvaliador.setLayout(PanelPrincipalAvaliadorLayout);
        PanelPrincipalAvaliadorLayout.setHorizontalGroup(
            PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BotaoAvaliarArtigos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BotaoAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BotaoLogoutAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        PanelPrincipalAvaliadorLayout.setVerticalGroup(
            PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(BotaoAvaliarArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoLogoutAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipalAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipalAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAvaliarArtigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAvaliarArtigosActionPerformed
        AvaliarArtigo cadastro = null;
        try {
            cadastro = new AvaliarArtigo(this, true, x);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAvaliador.class.getName()).log(Level.SEVERE, null, ex);
        }
        cadastro.setSize(1000,750);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoAvaliarArtigosActionPerformed

    private void BotaoLogoutAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoutAvaliadorActionPerformed
        this.dispose();
        Menu2 menu = new Menu2();
        menu.setVisible(true);
        menu.setDefaultCloseOperation(EXIT_ON_CLOSE);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_BotaoLogoutAvaliadorActionPerformed

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed
        AlterarConta cadastro = new AlterarConta(this, true, x);
        
        cadastro.setSize(605,400);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ExcluirContaAvaliador cadastro = new ExcluirContaAvaliador(this, true, x);      
        cadastro.setSize(605,400);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoAvaliarArtigos;
    private javax.swing.JButton BotaoLogoutAvaliador;
    private javax.swing.JPanel PanelPrincipalAvaliador;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
