/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno
 */
public class MenuAvaliador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAvaliador
     */
    public MenuAvaliador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalAvaliador = new javax.swing.JPanel();
        BotaoAvaliarArtigos = new javax.swing.JButton();
        BotaoLogoutAvaliador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Avaliador");

        PanelPrincipalAvaliador.setToolTipText("");

        BotaoAvaliarArtigos.setText("Avaliar artigos");
        BotaoAvaliarArtigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAvaliarArtigosActionPerformed(evt);
            }
        });

        BotaoLogoutAvaliador.setText("Logout");
        BotaoLogoutAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoutAvaliadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalAvaliadorLayout = new javax.swing.GroupLayout(PanelPrincipalAvaliador);
        PanelPrincipalAvaliador.setLayout(PanelPrincipalAvaliadorLayout);
        PanelPrincipalAvaliadorLayout.setHorizontalGroup(
            PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoLogoutAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAvaliarArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        PanelPrincipalAvaliadorLayout.setVerticalGroup(
            PanelPrincipalAvaliadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalAvaliadorLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(BotaoAvaliarArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoLogoutAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipalAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipalAvaliador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAvaliarArtigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAvaliarArtigosActionPerformed
        AvaliarArtigo cadastro = null;
        try {
            cadastro = new AvaliarArtigo(this, true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuAvaliador.class.getName()).log(Level.SEVERE, null, ex);
        }
        cadastro.setSize(1000,750);
        cadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
    }//GEN-LAST:event_BotaoAvaliarArtigosActionPerformed

    private void BotaoLogoutAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoutAvaliadorActionPerformed
        this.dispose();
        Menu2 menu = new Menu2();
        menu.setVisible(true);
        menu.setDefaultCloseOperation(EXIT_ON_CLOSE);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_BotaoLogoutAvaliadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAvaliador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAvaliador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAvaliador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAvaliador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAvaliador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAvaliarArtigos;
    private javax.swing.JButton BotaoLogoutAvaliador;
    private javax.swing.JPanel PanelPrincipalAvaliador;
    // End of variables declaration//GEN-END:variables
}
